### ISSUE TITLE
Windows users - solution for error 'Plugin "react" was conflicted between "package.json » eslint-config-react-app »' ...

### ISSUE THREAD

**Issue by jakebanks** [joy-of-react/word-clone#31]
Hey Josh,

Just flagging the following issue in case anyone else hits it. I'm not sure if raising an issue in the repo is appropriate as it is definitely not specific to your app. It feels wrong to suggest that you document it, but I'm hoping raising this issue can help somebody else.

When running `npm start` I see the above error message in the browser - solution found [here](https://stackoverflow.com/a/70391240).

Thanks!
Jake

**Comment by joshwcomeau** [comment]
Sorry for not seeing this sooner!

I'm migrating this app to use Parcel rather than Create React App, and so hopefully this won't be an issue anymore =)
